raw:
  fullnameOverride: ingress-class

  resources:
    # EKS Auto Mode built-in load balancing (ALB)
    - apiVersion: networking.k8s.io/v1
      kind: IngressClass
      metadata:
        name: alb
        annotations:
          ingressclass.kubernetes.io/is-default-class: "true"
      spec:
        controller: eks.amazonaws.com/alb
