argo-rollouts:
  fullnameOverride: argo-rollouts

raw:
  resources:
    - apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: argo-rollouts-notification-secret
      spec:
        refreshInterval: 1h
        secretStoreRef:
          kind: ClusterSecretStore
          name: parameter-store
        target:
          name: argo-rollouts-notification-secret
        data:
          - secretKey: slack-token
            remoteRef:
              key: /k8s/common/slack-token

    - apiVersion: argoproj.io/v1alpha1
      kind: ClusterAnalysisTemplate
      metadata:
        name: http-benchmark
      spec:
        args:
          - name: url
        metrics:
          - name: http-benchmark
            count: 3
            failureLimit: 3
            interval: 60s
            provider:
              job:
                spec:
                  template:
                    metadata:
                      annotations:
                        sidecar.istio.io/inject: "false"
                    spec:
                      containers:
                        - name: load-tester
                          image: argoproj/load-tester:latest
                          command: [sh, -xec]
                          args:
                            - |
                              wrk -t5 -c5 -d10 -s report.lua {{args.url}}
                              jq -e '.errors_ratio <= 0.1' report.json
                      restartPolicy: Never
                  activeDeadlineSeconds: 300
                  backoffLimit: 10
                  ttlSecondsAfterFinished: 600

    - apiVersion: argoproj.io/v1alpha1
      kind: ClusterAnalysisTemplate
      metadata:
        name: success-rate
      spec:
        args:
          - name: service-name
        metrics:
          - name: success-rate
            failureLimit: 3
            interval: 5m
            successCondition: result[0] >= 0.95
            provider:
              prometheus:
                address: http://prometheus-k8s.addon-monitoring.svc.cluster.local:9090
                query: |
                  sum(irate(
                    istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}",response_code!~"5.*"}[5m]
                  )) /
                  sum(irate(
                    istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}"}[5m]
                  ))
