apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: agent-studio-workspaces
  labels:
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  groups:
{{ toYaml .Values.workspaceAlerts.groups | indent 4 }}
