kube-prometheus-stack:
  fullnameOverride: prometheus

raw:
  resources:
    - apiVersion: networking.istio.io/v1beta1
      kind: Gateway
      metadata:
        name: prometheus
      spec:
        selector:
          istio: ingressgateway
        servers:
          - hosts:
              - "prom.{{hostname.internal}}"
            port:
              number: 80
              name: http
              protocol: HTTP

    - apiVersion: networking.istio.io/v1beta1
      kind: VirtualService
      metadata:
        name: prometheus
      spec:
        hosts:
          - "prom.{{hostname.internal}}"
        gateways:
          - prometheus
          - mesh
        http:
          - route:
              - destination:
                  host: prometheus-prometheus
                  port:
                    number: 9090
