promtail:
  fullnameOverride: promtail

  podLabels:
    owner: "{{cluster}}"
    department: "addons"

  # image:
  #   registry: {{promtail.image.registry}}
  #   repository: {{promtail.image.repository}}

  extraArgs:
    - -client.external-labels=cluster={{cluster}}

  config:
    clients:
      - url: http://{{loki.hostname}}/loki/api/v1/push

  # tolerations:
  #   - operator: Exists

  # updateStrategy:
  #   rollingUpdate:
  #     maxUnavailable: 25%
