aws-node-termination-handler:
  awsRegion: "ap-northeast-2"

  queueURL: "https://sqs.ap-northeast-2.amazonaws.com/396608815058/eks-demo-nth"



  managedTag: "aws-node-termination-handler/eks-demo"

  serviceMonitor:
    create: False

