istiod:
  # global:
  #   hub: "{{istio.global.hub}}"

  pilot:
    autoscaleEnabled: {{istio.pilot.autoscale}}
    replicaCount: {{istio.pilot.min}}
    autoscaleMin: {{istio.pilot.min}}
    autoscaleMax: {{istio.pilot.max}}

    podLabels:
      owner: "{{cluster}}"
      # department: "addons"

  meshConfig:
    defaultConfig:
      tracing:
        sampling: {{istio.tracing.sampling}}

gateway:
  replicaCount: {{istio.gateway.min}}

  autoscaling:
    enabled: {{istio.gateway.autoscale}}
    minReplicas: {{istio.gateway.min}}
    maxReplicas: {{istio.gateway.max}}

  labels:
    owner: "{{cluster}}"
    # department: "addons"

tgb:
  resources:
    - apiVersion: elbv2.k8s.aws/v1beta1
      kind: TargetGroupBinding
      metadata:
        name: istio-ingressgateway-public
      spec:
        serviceRef:
          name: istio-ingressgateway
          port: http2
        targetGroupARN: "{{istio.target_group.public_http}}"
        targetType: ip

    - apiVersion: elbv2.k8s.aws/v1beta1
      kind: TargetGroupBinding
      metadata:
        name: istio-ingressgateway-internal
      spec:
        serviceRef:
          name: istio-ingressgateway
          port: http2
        targetGroupARN: "{{istio.target_group.internal_http}}"
        targetType: ip
