metrics-server:
  fullnameOverride: metrics-server
  replicas: 2
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: metrics-server

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 512Mi

  # apiService:
  #   create: true

  # args:
  #   - --kubelet-insecure-tls
  #   - --kubelet-preferred-address-types=InternalIP
