apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alloy
spec:
  generators:
    - git:
        repoURL: https://github.com/opspresso/argocd-env-addons.git
        revision: HEAD
        files:
          - path: "env/eks-demo.yaml"

  template:
    metadata:
      name: "alloy-{{cluster}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: /charts/alloy
      labels:
        app.kubernetes.io/instance: "addons-{{cluster}}"
        opspresso.com/cluster: "{{cluster}}"
        opspresso.com/group: "addons"
    spec:
      project: addons
      destination:
        name: "{{cluster}}"
        namespace: addon-alloy
      source:
        repoURL: https://github.com/opspresso/argocd-env-addons.git
        targetRevision: HEAD
        path: charts/alloy
        helm:
          releaseName: alloy
          valueFiles:
            - values.yaml
            - "{{env}}/values-{{cluster}}.yaml"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
