istiod:
  # global:
  #   hub: "gcr.io/istio-release"

  pilot:
    autoscaleEnabled: False
    replicaCount: 2
    autoscaleMin: 2
    autoscaleMax: 2

    podLabels:
      owner: "eks-demo"
      # department: "addons"

  meshConfig:
    defaultConfig:
      tracing:
        sampling: 10

gateway:
  replicaCount: 2

  autoscaling:
    enabled: False
    minReplicas: 2
    maxReplicas: 5

  labels:
    owner: "eks-demo"
    # department: "addons"

tgb:
  resources:
    - apiVersion: elbv2.k8s.aws/v1beta1
      kind: TargetGroupBinding
      metadata:
        name: istio-ingressgateway-public
      spec:
        serviceRef:
          name: istio-ingressgateway
          port: http2
        targetGroupARN: "arn:aws:elasticloadbalancing:ap-northeast-2:082867736673:targetgroup/demo-http-0/08838a6c244f3faa"
        targetType: ip

    - apiVersion: elbv2.k8s.aws/v1beta1
      kind: TargetGroupBinding
      metadata:
        name: istio-ingressgateway-internal
      spec:
        serviceRef:
          name: istio-ingressgateway
          port: http2
        targetGroupARN: "arn:aws:elasticloadbalancing:ap-northeast-2:082867736673:targetgroup/demo-in-http-0/aefb7e177410595b"
        targetType: ip