istiod:
  global:
    hub: "gcr.io/istio-release"

  replicaCount: 3

  autoscaleEnabled: False
  autoscaleMin: 3
  autoscaleMax: 3

gateway:
  replicaCount: 3

  autoscaling:
    enabled: False
    minReplicas: 3
    maxReplicas: 3

tgb:
  resources:
    - apiVersion: elbv2.k8s.aws/v1beta1
      kind: TargetGroupBinding
      metadata:
        name: istio-ingressgateway-public
      spec:
        serviceRef:
          name: istio-ingressgateway
          port: http2
        targetGroupARN: "arn:aws:elasticloadbalancing:ap-northeast-2:396608815058:targetgroup/demo-http-b/ab1d7278dcab7ef5"
        targetType: ip

    - apiVersion: elbv2.k8s.aws/v1beta1
      kind: TargetGroupBinding
      metadata:
        name: istio-ingressgateway-internal
      spec:
        serviceRef:
          name: istio-ingressgateway
          port: http2
        targetGroupARN: "arn:aws:elasticloadbalancing:ap-northeast-2:396608815058:targetgroup/demo-in-http-b/479eae4e18d70dbe"
        targetType: ip