istiod:
  global:
    hub: "gcr.io/istio-release"

  replicaCount: 3

  autoscaleEnabled: False
  autoscaleMin: 3
  autoscaleMax: 3

gateway:
  replicaCount: 3

  autoscaling:
    enabled: False
    minReplicas: 3
    maxReplicas: 3

tgb:
  resources:
    - apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: istio-target-group
      spec:
        refreshInterval: 1h
        secretStoreRef:
          kind: ClusterSecretStore
          name: parameter-store
        target:
          name: istio-target-group
        data:
          - secretKey: target_group_public
            remoteRef:
              key: /k8s/common/demo/public_http_a
          - secretKey: target_group_internal
            remoteRef:
              key: /k8s/common/demo/internal_http_a

    - apiVersion: elbv2.k8s.aws/v1beta1
      kind: TargetGroupBinding
      metadata:
        name: istio-ingressgateway-public
      spec:
        serviceRef:
          name: istio-ingressgateway
          port: http2
        targetGroupARN: "arn:aws:elasticloadbalancing:ap-northeast-2:396608815058:targetgroup/demo-http-a/2d3c73b28d874d7d"
        targetType: ip

    - apiVersion: elbv2.k8s.aws/v1beta1
      kind: TargetGroupBinding
      metadata:
        name: istio-ingressgateway-internal
      spec:
        serviceRef:
          name: istio-ingressgateway
          port: http2
        targetGroupARN: "arn:aws:elasticloadbalancing:ap-northeast-2:396608815058:targetgroup/demo-in-http-a/bb4396c62c719758"
        targetType: ip