istiod:
  global:
    hub: "gcr.io/istio-release"

  pilot:
    autoscaleEnabled: False
    replicaCount: 2
    autoscaleMin: 2
    autoscaleMax: 2

    podLabels:
      owner: "eks-demo-a"
      # department: "addons"

  meshConfig:
    defaultConfig:
      tracing:
        sampling: 10

gateway:
  replicaCount: 2

  autoscaling:
    enabled: False
    minReplicas: 2
    maxReplicas: 5

  labels:
    owner: "eks-demo-a"
    # department: "addons"

tgb:
  resources:
    - apiVersion: elbv2.k8s.aws/v1beta1
      kind: TargetGroupBinding
      metadata:
        name: istio-ingressgateway-public
      spec:
        serviceRef:
          name: istio-ingressgateway
          port: http2
        targetGroupARN: "arn:aws:elasticloadbalancing:ap-northeast-2:396608815058:targetgroup/demo-http-a/ecaf6eeb5a715cc9"
        targetType: ip

    - apiVersion: elbv2.k8s.aws/v1beta1
      kind: TargetGroupBinding
      metadata:
        name: istio-ingressgateway-internal
      spec:
        serviceRef:
          name: istio-ingressgateway
          port: http2
        targetGroupARN: "arn:aws:elasticloadbalancing:ap-northeast-2:396608815058:targetgroup/demo-in-http-a/140c9abc47d4684e"
        targetType: ip