istiod:
  global:
    hub: "gcr.io/istio-release"

  pilot:
    autoscaleEnabled: False
    replicaCount: 2
    autoscaleMin: 2
    autoscaleMax: 2

  meshConfig:
    defaultConfig:
      tracing:
        sampling: 10

gateway:
  replicaCount: 2

  autoscaling:
    enabled: False
    minReplicas: 2
    maxReplicas: 5

tgb:
  resources:
    - apiVersion: elbv2.k8s.aws/v1beta1
      kind: TargetGroupBinding
      metadata:
        name: istio-ingressgateway-public
      spec:
        serviceRef:
          name: istio-ingressgateway
          port: http2
        targetGroupARN: "arn:aws:elasticloadbalancing:ap-northeast-2:396608815058:targetgroup/demo-http-0/a766fcc903146b7d"
        targetType: ip

    - apiVersion: elbv2.k8s.aws/v1beta1
      kind: TargetGroupBinding
      metadata:
        name: istio-ingressgateway-internal
      spec:
        serviceRef:
          name: istio-ingressgateway
          port: http2
        targetGroupARN: "arn:aws:elasticloadbalancing:ap-northeast-2:396608815058:targetgroup/demo-in-http-0/1ce364d032be7b33"
        targetType: ip