istiod:
  global:
    hub: "gcr.io/istio-release"

  replicaCount: 2

  autoscaleEnabled: False
  autoscaleMin: 2
  autoscaleMax: 6

gateway:
  replicaCount: 2

  autoscaling:
    enabled: False
    minReplicas: 2
    maxReplicas: 6

tgb:
  resources:
    - apiVersion: eks.amazonaws.com/v1
      kind: TargetGroupBinding
      metadata:
        name: istio-ingressgateway-public
      spec:
        serviceRef:
          name: istio-ingressgateway
          port: http2
        targetGroupARN: "arn:aws:elasticloadbalancing:ap-northeast-2:396608815058:targetgroup/demo-h1-a/92eba81747265fdd"
        targetType: ip

    - apiVersion: eks.amazonaws.com/v1
      kind: TargetGroupBinding
      metadata:
        name: istio-ingressgateway-internal
      spec:
        serviceRef:
          name: istio-ingressgateway
          port: http2
        targetGroupARN: "arn:aws:elasticloadbalancing:ap-northeast-2:396608815058:targetgroup/demo-in-http-a/006cd49a0edd2e69"
        targetType: ip
