fullnameOverride: argocd

global:
  domain: ARGOCD_HOSTNAME

server:
  replicas: 1

  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: ARGOCD_HOSTNAME
    tls: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"

repoServer:
  replicas: 1

controller:
  replicas: 1

dex:
  enabled: false

notifications:
  enabled: false

configs:
  params:
    server.insecure: true

  cm:
    url: https://ARGOCD_HOSTNAME
