cluster-autoscaler:
  awsRegion: "ap-northeast-2"

  autoDiscovery:
    clusterName: "eks-demo"


  extraArgs:

    scan-interval: "20s"


    scale-down-delay-after-delete: "1m"




    scale-down-utilization-threshold: "0.6"




  serviceMonitor:
    enabled: False

