apiVersion: v2
appVersion: v1.7.5
dependencies:
- name: argo-events
  repository: https://argoproj.github.io/argo-helm
  version: 2.1.2
description: A Helm chart for Kubernetes
name: argo-events
type: application
version: 2.1.2-4f4a062
