argo-rollouts:
  fullnameOverride: argo-rollouts

  controller:
    resources:
      requests:
        cpu: 256m
        memory: 1Gi
      limits:
        memory: 1Gi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: False
        namespace: addon-argo-rollouts

  dashboard:
    enabled: true

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

    podAnnotations:
      link.argocd.argoproj.io/external-link: "https://rollouts.demo.opspresso.com"

    ingress:
      enabled: false
      ingressClassName: "nginx"
      hosts:
        - "rollouts.demo.opspresso.com"