argo-rollouts:
  fullnameOverride: argo-rollouts

  controller:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: False
        namespace: addon-argo-rollouts

  dashboard:
    podAnnotations:
      link.argocd.argoproj.io/external-link: "https://rollouts.demo.opspresso.com"

    ingress:
      enabled: false
      ingressClassName: "nginx"
      hosts:
        - "rollouts.demo.opspresso.com"

route:
  resources:
    - apiVersion: networking.istio.io/v1beta1
      kind: Gateway
      metadata:
        name: argo-rollouts-dashboard
      spec:
        selector:
          istio: ingressgateway
        servers:
          - hosts:
              - "rollouts.demo.opspresso.com"
            port:
              number: 80
              name: http
              protocol: HTTP

    - apiVersion: networking.istio.io/v1beta1
      kind: VirtualService
      metadata:
        name: argo-rollouts-dashboard
      spec:
        hosts:
          - "rollouts.demo.opspresso.com"
        gateways:
          - argo-rollouts-dashboard
        http:
          - route:
              - destination:
                  host: argo-rollouts-dashboard
                  port:
                    number: 3100

    - apiVersion: security.istio.io/v1beta1
      kind: AuthorizationPolicy
      metadata:
        name: oauth2-proxy-rollouts
        namespace: istio-system
      spec:
        selector:
          matchLabels:
            istio: ingressgateway
        action: CUSTOM
        provider:
          name: oauth2-proxy-rollouts
        rules:
        - to:
          - operation:
              hosts:
              - "rollouts.demo.opspresso.com"