apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons-demo
  namespace: default
  labels:
    krmt.io/group: addons
spec:
  project: addons
  source:
    repoURL: https://github.com/opspresso/argocd-env-addons
    targetRevision: HEAD
    path: addons
  destination:
    name: eks-demo
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
