apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-events
spec:
  generators:
    - git:
        repoURL: https://github.com/opspresso/argocd-env-addons.git
        revision: HEAD
        files:
          - path: "env/eks-demo.yaml"

  template:
    metadata:
      name: "argo-events" # only management cluster
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: noti-argocd-{{cluster_env}}-addon
      labels:
        app.kubernetes.io/instance: "addons-{{cluster}}"
        krmt.io/cluster: "{{cluster}}"
        krmt.io/group: "addons"
    spec:
      project: addons
      destination:
        name: "{{cluster}}"
        namespace: addon-argo-events
      source:
        repoURL: https://argoproj.github.io/argo-helm
        targetRevision: "2.0.3"
        chart: argo-events
        helm:
          values: |-
            fullnameOverride: argo-events

      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
          - CreateNamespace=true
