apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aws-load-balancer-controller
spec:
  generators:
    - git:
        repoURL: https://github.com/opspresso/argocd-env-addons.git
        revision: HEAD
        files:
          - path: "env/eks-demo.yaml"
          # - path: "env/eks-demo-a.yaml"
          # - path: "env/eks-demo-b.yaml"

  template:
    metadata:
      name: "aws-load-balancer-controller-{{cluster}}"
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: noti-argocd-{{cluster_env}}-addon
      labels:
        app.kubernetes.io/instance: "addons-{{cluster}}"
        krmt.io/cluster: "{{cluster}}"
        krmt.io/group: "addons"
    spec:
      project: addons
      destination:
        name: "{{cluster}}"
        namespace: addon-aws-load-balancer-controller
      source:
        repoURL: https://aws.github.io/eks-charts
        targetRevision: "1.4.2"
        chart: aws-load-balancer-controller
        helm:
          values: |-
            fullnameOverride: aws-load-balancer-controller

            clusterName: "{{cluster}}"

            podLabels:
              krmt.io/cluster: "{{cluster}}"
              krmt.io/group: "addons"

            serviceAccount:
              annotations:
                eks.amazonaws.com/role-arn: "arn:aws:iam::{{aws_account_id}}:role/irsa--{{cluster}}--aws-load-balancer-controller"

            # tolerations:
            #   - key: group
            #     operator: Equal
            #     value: graviton
            #     effect: NoSchedule
            # nodeSelector:
            #   group: graviton

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
