apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aws-efs-csi-driver
spec:
  generators:
    - git:
        repoURL: https://github.com/opspresso/argocd-env-addons.git
        revision: HEAD
        files:
          - path: "env/eks-demo.yaml"
          # - path: "env/eks-demo-a.yaml"
          # - path: "env/eks-demo-b.yaml"

  template:
    metadata:
      name: "aws-efs-csi-driver-{{cluster}}"
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: noti-argocd-{{cluster_env}}-addon
      labels:
        app.kubernetes.io/instance: "addons-{{cluster}}"
        krmt.io/cluster: "{{cluster}}"
        krmt.io/group: "addons"
    spec:
      project: addons
      destination:
        name: "{{cluster}}"
        namespace: addon-aws-efs-csi-driver
      source:
        repoURL: https://kubernetes-sigs.github.io/aws-efs-csi-driver
        targetRevision: "2.2.7"
        chart: aws-efs-csi-driver
        helm:
          values: |-
            fullnameOverride: aws-efs-csi-driver

            controller:
              podLabels:
                owner: "{{cluster}}"
                department: "addons"

              serviceAccount:
                annotations:
                  eks.amazonaws.com/role-arn: "arn:aws:iam::{{aws_account_id}}:role/irsa--{{cluster}}--aws-efs-csi-driver"

              # tolerations:
              #   - key: group
              #     operator: Equal
              #     value: graviton
              #     effect: NoSchedule
              # nodeSelector:
              #   group: graviton

            node:
              podLabels:
                owner: "{{cluster}}"
                department: "addons"

              serviceAccount:
                annotations:
                  eks.amazonaws.com/role-arn: "arn:aws:iam::{{aws_account_id}}:role/irsa--{{cluster}}--aws-efs-csi-driver"

              tolerations:
                # - operator: Exists
                - key: group
                  operator: Equal
                  value: workers
                  effect: NoSchedule

            storageClasses:
              - name: efs
                mountOptions:
                  - tls
                parameters:
                  basePath: "/shared"
                  directoryPerms: "755"
                  fileSystemId: "{{aws-efs-csi-driver.efs-id}}"
                  gidRangeEnd: "2000"
                  gidRangeStart: "1000"
                  provisioningMode: efs-ap
                reclaimPolicy: Retain
                allowVolumeExpansion: true

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
