apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-autoscaler-extra
spec:
  generators:
    - git:
        repoURL: https://github.com/opspresso/argocd-env-addons.git
        revision: HEAD
        files:
          - path: "env/eks-demo.yaml"
          # - path: "env/eks-demo-a.yaml"
          # - path: "env/eks-demo-b.yaml"

  template:
    metadata:
      name: "cluster-autoscaler-extra-{{cluster}}"
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: noti-argocd-{{cluster_env}}-addon
      labels:
        app.kubernetes.io/instance: "addons-{{cluster}}"
        krmt.io/cluster: "{{cluster}}"
        krmt.io/group: "addons"
    spec:
      project: addons
      destination:
        name: "{{cluster}}"
        namespace: addon-cluster-autoscaler
      source:
        repoURL: https://charts.helm.sh/incubator
        targetRevision: "0.2.5"
        chart: raw
        helm:
          values: |-
            fullnameOverride: cluster-autoscaler-extra

            resources:
              - apiVersion: irsa.voodoo.io/v1alpha1
                kind: IamRoleServiceAccount
                metadata:
                  name: cluster-autoscaler
                spec:
                  # serviceAccountName: cluster-autoscaler
                  policy:
                    statement:
                    - action:
                        - "autoscaling:DescribeAutoScalingGroups"
                        - "autoscaling:DescribeAutoScalingInstances"
                        - "autoscaling:DescribeLaunchConfigurations"
                        - "autoscaling:DescribeTags"
                        - "autoscaling:SetDesiredCapacity"
                        - "autoscaling:TerminateInstanceInAutoScalingGroup"
                        - "autoscaling:UpdateAutoScalingGroup"
                        - "ec2:DescribeLaunchTemplateVersions"
                        - "ec2:DescribeInstanceTypes"
                      resource: "*"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
