apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-storage-class
spec:
  generators:
    - git:
        repoURL: https://github.com/opspresso/argocd-env-addons.git
        revision: HEAD
        files:
          - path: "env/eks-demo.yaml"
          # - path: "env/eks-demo-a.yaml"
          # - path: "env/eks-demo-b.yaml"

  template:
    metadata:
      name: "cluster-storage-class-{{cluster}}"
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: noti-argocd-{{env}}-addon
      labels:
        app.kubernetes.io/instance: "addons-{{cluster}}"
        krmt.io/cluster: "{{cluster}}"
        krmt.io/group: "addons"
    spec:
      project: addons
      destination:
        name: "{{cluster}}"
        namespace: default
      source:
        repoURL: https://charts.helm.sh/incubator
        targetRevision: "0.2.5"
        chart: raw
        helm:
          values: |-
            fullnameOverride: cluster-storage-class

            resources:
              - apiVersion: storage.k8s.io/v1
                kind: StorageClass
                metadata:
                  name: gp3
                provisioner: ebs.csi.aws.com
                volumeBindingMode: WaitForFirstConsumer
                parameters:
                  type: gp3
                  allowAutoIOPSPerGBIncrease: "true"
                reclaimPolicy: Retain
                allowVolumeExpansion: true

              - apiVersion: storage.k8s.io/v1
                kind: StorageClass
                metadata:
                  name: gp3-a
                provisioner: ebs.csi.aws.com
                volumeBindingMode: WaitForFirstConsumer
                parameters:
                  type: gp3
                  allowAutoIOPSPerGBIncrease: "true"
                reclaimPolicy: Retain
                allowVolumeExpansion: true
                allowedTopologies:
                - matchLabelExpressions:
                  - key: topology.ebs.csi.aws.com/zone
                    values:
                    - {{aws_region}}a

              - apiVersion: storage.k8s.io/v1
                kind: StorageClass
                metadata:
                  name: gp3-b
                provisioner: ebs.csi.aws.com
                volumeBindingMode: WaitForFirstConsumer
                parameters:
                  type: gp3
                  allowAutoIOPSPerGBIncrease: "true"
                reclaimPolicy: Retain
                allowVolumeExpansion: true
                allowedTopologies:
                - matchLabelExpressions:
                  - key: topology.ebs.csi.aws.com/zone
                    values:
                    - {{aws_region}}b

              - apiVersion: storage.k8s.io/v1
                kind: StorageClass
                metadata:
                  name: gp3-c
                provisioner: ebs.csi.aws.com
                volumeBindingMode: WaitForFirstConsumer
                parameters:
                  type: gp3
                  allowAutoIOPSPerGBIncrease: "true"
                reclaimPolicy: Retain
                allowVolumeExpansion: true
                allowedTopologies:
                - matchLabelExpressions:
                  - key: topology.ebs.csi.aws.com/zone
                    values:
                    - {{aws_region}}c

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
