apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-info
spec:
  generators:
    - git:
        repoURL: https://github.com/opspresso/argocd-env-addons.git
        revision: HEAD
        files:
          - path: "env/eks-demo.yaml"
          # - path: "env/eks-demo-a.yaml"
          # - path: "env/eks-demo-b.yaml"

  template:
    metadata:
      name: "cluster-info-{{cluster}}"
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: noti-argocd-{{env}}-addon
      labels:
        app.kubernetes.io/instance: "addons-{{cluster}}"
        krmt.io/cluster: "{{cluster}}"
        krmt.io/group: "addons"
    spec:
      project: addons
      destination:
        name: "{{cluster}}"
        namespace: default
      source:
        repoURL: https://charts.helm.sh/incubator
        targetRevision: "0.2.5"
        chart: raw
        helm:
          values: |-
            fullnameOverride: cluster-info

            resources:
              - apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: cluster-info
                data:
                  AWS_ACCOUNT_ID: "{{aws_account_id}}"
                  AWS_REGION: "{{aws_region}}"
                  CLUSTER: "{{cluster}}"
                  COUNTRY: "{{country}}"
                  ENV: "{{env}}"
                  ROLE: "{{role}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
