apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: crossplane-extra
spec:
  generators:
    - git:
        repoURL: https://github.com/opspresso/argocd-env-demo.git
        revision: HEAD
        files:
          - path: "env/eks-demo.yaml"
          # - path: "env/eks-demo-a.yaml"
          # - path: "env/eks-demo-b.yaml"

  template:
    metadata:
      name: "crossplane-extra-{{cluster}}"
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: noti-argocd-{{env}}-addon
      labels:
        app.kubernetes.io/instance: "addons-{{cluster}}"
        krmt.io/cluster: "{{cluster}}"
        krmt.io/group: "addons"
    spec:
      project: addons
      destination:
        name: "{{cluster}}"
        namespace: addon-crossplane
      source:
        repoURL: https://charts.helm.sh/incubator
        targetRevision: "0.2.5"
        chart: raw
        helm:
          values: |-
            fullnameOverride: crossplane-extra

            resources:
              - apiVersion: pkg.crossplane.io/v1
                kind: Provider
                metadata:
                  name: provider-aws
                spec:
                  package: "crossplane/provider-aws:v0.34.0"
                  # https://github.com/crossplane/provider-aws

              - apiVersion: external-secrets.io/v1beta1
                kind: ExternalSecret
                metadata:
                  name: crossplane-cred-aws-bruce-ops
                spec:
                  refreshInterval: 1h
                  secretStoreRef:
                    kind: ClusterSecretStore
                    name: parameter-store
                  target:
                    name: crossplane-cred-aws-bruce-ops
                  data:
                    - secretKey: credentials
                      remoteRef:
                        key: /k8s/common/crossplane-cred-aws-bruce-ops

              - apiVersion: aws.crossplane.io/v1beta1
                kind: ProviderConfig
                metadata:
                  name: aws-bruce-ops
                spec:
                  credentials:
                    source: Secret
                    secretRef:
                      name: crossplane-cred-aws-bruce-ops
                      namespace: addon-crossplane
                      key: credentials

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
