apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns
spec:
  generators:
    - git:
        repoURL: https://github.com/opspresso/argocd-env-addons.git
        revision: HEAD
        files:
          - path: "env/eks-demo.yaml"

  template:
    metadata:
      name: "external-dns"
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: noti-argocd-{{env}}-addon
      labels:
        app.kubernetes.io/instance: "addons-{{cluster}}"
        krmt.io/cluster: "{{cluster}}"
        krmt.io/group: "addons"
    spec:
      project: addons
      destination:
        name: "{{cluster}}"
        namespace: addon-external-dns
      source:
        repoURL: https://kubernetes-sigs.github.io/external-dns
        targetRevision: "1.11.0"
        chart: external-dns
        helm:
          values: |-
            fullnameOverride: external-dns

            podLabels:
              owner: "{{cluster}}"
              department: "addons"

            sources:
              - ingress
              - service

            serviceAccount:
              annotations:
                eks.amazonaws.com/role-arn: "arn:aws:iam::{{aws_account_id}}:role/irsa--{{cluster}}--external-dns"

            # tolerations:
            #   - key: group
            #     operator: Equal
            #     value: graviton
            #     effect: NoSchedule
            # nodeSelector:
            #   group: graviton

      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
          - CreateNamespace=true
