apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
spec:
  generators:
    - git:
        repoURL: https://github.com/opspresso/argocd-env-addons.git
        revision: HEAD
        files:
          - path: "env/eks-demo.yaml"
          # - path: "env/eks-demo-a.yaml"
          # - path: "env/eks-demo-b.yaml"

  template:
    metadata:
      name: "external-secrets-{{cluster}}"
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: noti-argocd-{{env}}-addon
      labels:
        app.kubernetes.io/instance: "addons-{{cluster}}"
        krmt.io/cluster: "{{cluster}}"
        krmt.io/group: "addons"
    spec:
      project: addons
      destination:
        name: "{{cluster}}"
        namespace: addon-external-secrets
      source:
        repoURL: https://charts.external-secrets.io
        targetRevision: "0.5.7"
        chart: external-secrets
        helm:
          values: |-
            fullnameOverride: external-secrets

            podLabels:
              owner: "{{cluster}}"
              department: "addons"

            serviceAccount:
              annotations:
                eks.amazonaws.com/role-arn: "arn:aws:iam::{{aws_account_id}}:role/irsa--{{cluster}}--external-secrets"

            webhook:
              podLabels:
                owner: "{{cluster}}"
                department: "addons"

            certController:
              podLabels:
                owner: "{{cluster}}"
                department: "addons"

      ignoreDifferences:
        - kind: CustomResourceDefinition
          group: apiextensions.k8s.io
          jsonPointers:
            - /spec/conversion/webhook/clientConfig
        - kind: ValidatingWebhookConfiguration
          group: admissionregistration.k8s.io
          jsonPointers:
            - /webhooks/0/clientConfig/caBundle
            - /webhooks/1/clientConfig/caBundle

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
