apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana
spec:
  generators:
    - git:
        repoURL: https://github.com/opspresso/argocd-env-addons.git
        revision: HEAD
        files:
          - path: "env/eks-demo.yaml"

  template:
    metadata:
      name: "grafana" # only management cluster
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: noti-argocd-{{env}}-addon
      labels:
        app.kubernetes.io/instance: "addons-{{cluster}}"
        krmt.io/cluster: "{{cluster}}"
        krmt.io/group: "addons"
    spec:
      project: addons
      destination:
        name: "{{cluster}}"
        namespace: addon-grafana
      source:
        repoURL: https://grafana.github.io/helm-charts
        targetRevision: "6.43.4"
        chart: grafana
        helm:
          values: |-
            fullnameOverride: grafana

            revisionHistoryLimit: 3

            podLabels:
              owner: "{{cluster}}"
              department: "addons"

            podAnnotations:
              link.argocd.argoproj.io/external-link: "https://{{grafana.hostname}}"

            admin:
              existingSecret: "grafana-secret"

            extraSecretMounts:
              - name: grafana-secret
                secretName: grafana-secret
                defaultMode: 0440
                mountPath: /etc/secrets/grafana-secret
                readOnly: true

            grafana.ini:
              server:
                root_url: "https://{{grafana.hostname}}/"

              users:
                allow_sign_up: false
                auto_assign_org: true
                auto_assign_org_role: Admin

              auth:
                disable_login_form: false

              # https://grafana.com/docs/grafana/latest/auth/github/
              auth.github:
                enabled: {{grafana.auth.github.enabled}}
                allow_sign_up: true
                client_id: $__file{/etc/secrets/grafana-secret/github-id}
                client_secret: $__file{/etc/secrets/grafana-secret/github-secret}
                scopes: user:email,read:org
                auth_url: https://github.com/login/oauth/authorize
                token_url: https://github.com/login/oauth/access_token
                api_url: https://api.github.com/user
                allowed_organizations: {{grafana.auth.github.org}}
                # team_ids: {{grafana.auth.github.team_ids}}

              # https://grafana.com/docs/grafana/latest/auth/google/
              auth.google:
                enabled: {{grafana.auth.google.enabled}}
                allow_sign_up: true
                client_id: $__file{/etc/secrets/grafana-secret/google-id}
                client_secret: $__file{/etc/secrets/grafana-secret/google-secret}
                scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
                auth_url: https://accounts.google.com/o/oauth2/auth
                token_url: https://accounts.google.com/o/oauth2/token
                allowed_domains: {{grafana.auth.google.allowed_domains}}

            ingress:
              enabled: false

            datasources:
              datasources.yaml:
                apiVersion: 1
                datasources:
                - name: Prometheus
                  type: prometheus
                  url: http://prometheus-prometheus.addon-prometheus.svc.cluster.local:9090
                  access: proxy
                  isDefault: true
                - name: demo
                  type: prometheus
                  url: {{grafana.datasource.demo}}
                  access: proxy
                - name: demo-a
                  type: prometheus
                  url: {{grafana.datasource.demo-a}}
                  access: proxy
                - name: demo-b
                  type: prometheus
                  url: {{grafana.datasource.demo-b}}
                  access: proxy
                - name: Loki
                  type: loki
                  url: {{grafana.datasource.loki}}
                  access: proxy

            dashboardProviders:
              dashboardproviders.yaml:
                apiVersion: 1
                providers:
                - name: 'default'
                  orgId: 1
                  folder: ''
                  type: file
                  disableDeletion: false
                  editable: true
                  options:
                    path: /var/lib/grafana/dashboards/default

            dashboards:
              default:
                kube-cluster:
                  url: https://raw.githubusercontent.com/nalbam/kubernetes/master/grafana/kube-cluster.json
                  # gnetId: 9797
                  # revision: 18
                  # datasource: Prometheus
                kube-deploy:
                  url: https://raw.githubusercontent.com/nalbam/kubernetes/master/grafana/kube-deployment.json
                  # gnetId: 9679
                  # revision: 14
                  # datasource: Prometheus
                kube-sts:
                  url: https://raw.githubusercontent.com/nalbam/kubernetes/master/grafana/kube-statefulset.json
                  # gnetId: 14902
                  # revision: 4
                  # datasource: Prometheus
                kube-dms:
                  url: https://raw.githubusercontent.com/nalbam/kubernetes/master/grafana/kube-daemonset.json
                  # gnetId: 14982
                  # revision: 2
                  # datasource: Prometheus

                kubecost:
                  url: https://raw.githubusercontent.com/kubecost/cost-analyzer-helm-chart/develop/cost-analyzer/cluster-metrics.json
                  datasource: Prometheus

                jvm:
                  url: https://raw.githubusercontent.com/nalbam/kubernetes/master/grafana/jvm.json
                  datasource: Prometheus

                nginx-ingress:
                  url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/nginx.json
                  datasource: Prometheus

                argo-cd:
                  url: https://raw.githubusercontent.com/argoproj/argo-cd/master/examples/dashboard.json
                  datasource: Prometheus
                argo-rollouts:
                  url: https://raw.githubusercontent.com/argoproj/argo-rollouts/master/examples/dashboard.json
                  datasource: Prometheus

                istio-extension-dashboard:
                  url: https://raw.githubusercontent.com/nalbam/kubernetes/master/grafana/istio-extension-dashboard.json
                  datasource: Prometheus
                istio-mesh-dashboard:
                  url: https://raw.githubusercontent.com/nalbam/kubernetes/master/grafana/istio-mesh-dashboard.json
                  datasource: Prometheus
                istio-performance-dashboard:
                  url: https://raw.githubusercontent.com/nalbam/kubernetes/master/grafana/istio-performance-dashboard.json
                  datasource: Prometheus
                istio-service-dashboard:
                  url: https://raw.githubusercontent.com/nalbam/kubernetes/master/grafana/istio-service-dashboard.json
                  datasource: Prometheus
                istio-workload-dashboard:
                  url: https://raw.githubusercontent.com/nalbam/kubernetes/master/grafana/istio-workload-dashboard.json
                  datasource: Prometheus
                pilot-dashboard:
                  url: https://raw.githubusercontent.com/nalbam/kubernetes/master/grafana/istio-pilot-dashboard.json
                  datasource: Prometheus

            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce
              size: 5Gi
              storageClassName: gp3 # aws-ebs-sc

            serviceMonitor:
              enabled: true
              labels:
                release: prometheus-{{cluster}}

            tolerations:
              - key: group
                operator: Equal
                value: monitoring
                effect: NoSchedule
            nodeSelector:
              group: monitoring

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
