apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubecost
spec:
  generators:
    - git:
        repoURL: https://github.com/opspresso/argocd-env-addons.git
        revision: HEAD
        files:
          - path: "env/eks-demo.yaml"
          # - path: "env/eks-demo-a.yaml"
          # - path: "env/eks-demo-b.yaml"

  template:
    metadata:
      name: "kubecost-{{cluster}}"
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: noti-argocd-{{cluster_env}}-addon
      labels:
        app.kubernetes.io/instance: "addons-{{cluster}}"
        krmt.io/cluster: "{{cluster}}"
        krmt.io/group: "addons"
    spec:
      project: addons
      destination:
        name: "{{cluster}}"
        namespace: addon-kubecost
      source:
        repoURL: https://kubecost.github.io/cost-analyzer
        targetRevision: "1.94.3"
        chart: cost-analyzer
        helm:
          values: |-
            # fullnameOverride: kubecost

            global:
              prometheus:
                enabled: false
                fqdn: prometheus-prometheus.addon-prometheus.svc.cluster.local:9090
              grafana:
                enabled: false
                fqdn: grafana.addon-grafana.svc.cluster.local

            serviceMonitor:
              enabled: true
              additionalLabels:
                release: prometheus-{{cluster}}

            tolerations:
              - key: group
                operator: Equal
                value: monitoring
                effect: NoSchedule
            nodeSelector:
              group: monitoring

            # prometheus:
            #   server:
            #     persistentVolume:
            #       storageClass: gp3
            #     tolerations:
            #       - key: group
            #         operator: Equal
            #         value: monitoring
            #         effect: NoSchedule
            #     nodeSelector:
            #       group: monitoring

            #   # kubeStateMetrics:
            #   #   # enabled: false

            #   # nodeExporter:
            #   #   # enabled: false
            #   #   tolerations:
            #   #     - operator: Exists

            # grafana:
            #   datasources:
            #     datasources.yaml:
            #       apiVersion: 1
            #       datasources:
            #         - name: prometheus-kubecost
            #           type: prometheus
            #           url: http://prometheus-prometheus.addon-prometheus.svc.cluster.local:9090

            persistentVolume:
              storageClass: gp3
              size: 32Gi

      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
          - CreateNamespace=true
