apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubecost
spec:
  generators:
    - git:
        repoURL: https://github.com/opspresso/argocd-env-addons.git
        revision: HEAD
        files:
          - path: "env/eks-demo.yaml"
          # - path: "env/eks-demo-a.yaml"
          # - path: "env/eks-demo-b.yaml"

  template:
    metadata:
      name: "kubecost-{{cluster}}"
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: noti-argocd-{{cluster_env}}-addon
      labels:
        app.kubernetes.io/instance: "addons-{{cluster}}"
        krmt.io/cluster: "{{cluster}}"
        krmt.io/group: "addons"
    spec:
      project: addons
      destination:
        name: "{{cluster}}"
        namespace: addon-kubecost
      source:
        repoURL: https://kubecost.github.io/cost-analyzer
        targetRevision: "1.94.3"
        chart: cost-analyzer
        helm:
          values: |-
            fullnameOverride: kubecost

            global:
              prometheus:
                enabled: false
                fqdn: http://prometheus-prometheus.addon-prometheus.svc.cluster.local:9090
              grafana:
                enabled: false
                domainName: "{{grafana.hostname}}"
                scheme: https

            serviceAccount:
              annotations:
                eks.amazonaws.com/role-arn: "arn:aws:iam::{{aws_account_id}}:role/irsa--{{cluster}}--kubecost"

            # networkCosts:
            #   enabled: true
            #   config:
            #     services:
            #       amazon-web-services: true

            reporting:
              valuesReporting: false

            # serviceMonitor:
            #   enabled: true
            #   additionalLabels:
            #     release: prometheus-{{cluster}}

            # prometheusRule:
            #   enabled: true
            #   additionalLabels:
            #     release: prometheus-{{cluster}}

            tolerations:
              - key: group
                operator: Equal
                value: monitoring
                effect: NoSchedule
            nodeSelector:
              group: monitoring

            persistentVolume:
              storageClass: gp3
              size: 32Gi

            prometheus:
              server:
                global:
                  external_labels:
                    cluster_id: {{cluster}}

            kubecostMetrics:
              emitKsmV1Metrics: false # emit all KSM metrics in KSM v1.
              emitKsmV1MetricsOnly: true # emit only the KSM metrics missing from KSM v2. Advanced users only.

      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
          - CreateNamespace=true
