apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubecost-extra
spec:
  generators:
    - git:
        repoURL: https://github.com/opspresso/argocd-env-addons.git
        revision: HEAD
        files:
          - path: "env/eks-demo.yaml"
          # - path: "env/eks-demo-a.yaml"
          # - path: "env/eks-demo-b.yaml"

  template:
    metadata:
      name: "kubecost-extra-{{cluster}}"
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: noti-argocd-{{env}}-addon
      labels:
        app.kubernetes.io/instance: "addons-{{cluster}}"
        krmt.io/cluster: "{{cluster}}"
        krmt.io/group: "addons"
    spec:
      project: addons
      destination:
        name: "{{cluster}}"
        namespace: addon-kubecost
      source:
        repoURL: https://charts.helm.sh/incubator
        targetRevision: "0.2.5"
        chart: raw
        helm:
          values: |-
            fullnameOverride: kubecost-extra

            resources:
              - apiVersion: networking.istio.io/v1beta1
                kind: Gateway
                metadata:
                  name: kubecost
                spec:
                  selector:
                    istio: ingressgateway
                  servers:
                    - hosts:
                        - "{{kubecost.hostname}}"
                      port:
                        number: 80
                        name: http
                        protocol: HTTP

              - apiVersion: networking.istio.io/v1beta1
                kind: VirtualService
                metadata:
                  name: kubecost
                spec:
                  hosts:
                    - "{{kubecost.hostname}}"
                  gateways:
                    - kubecost
                    - mesh
                  http:
                    - route:
                        - destination:
                            host: kubecost-{{cluster}}-cost-analyzer
                            port:
                              number: 9090

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
