apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: loki
spec:
  generators:
    - git:
        repoURL: https://github.com/opspresso/argocd-env-addons.git
        revision: HEAD
        files:
          - path: "env/eks-demo.yaml"

  template:
    metadata:
      name: "loki" # only management cluster
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: noti-argocd-{{env}}-addon
      labels:
        app.kubernetes.io/instance: "addons-{{cluster}}"
        opspresso.com/cluster: "{{cluster}}"
        opspresso.com/group: "addons"
    spec:
      project: addons
      destination:
        name: "{{cluster}}"
        namespace: addon-loki
      source:
        repoURL: https://github.com/opspresso/argocd-env-addons.git
        targetRevision: HEAD
        path: charts/loki-stack
        helm:
          valueFiles:
            - values.yaml
            - "{{env}}/values-{{cluster}}.yaml"

      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
          - CreateNamespace=true
