apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: oauth2-proxy
spec:
  generators:
    - git:
        repoURL: https://github.com/opspresso/argocd-env-addons.git
        revision: HEAD
        files:
          - path: "env/eks-demo.yaml"

  template:
    metadata:
      name: "oauth2-proxy" # only management cluster
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: noti-argocd-{{env}}-addon
      labels:
        app.kubernetes.io/instance: "addons-{{cluster}}"
        krmt.io/cluster: "{{cluster}}"
        krmt.io/group: "addons"
    spec:
      project: addons
      destination:
        name: "{{cluster}}"
        namespace: addon-oauth2-proxy
      source:
        repoURL: https://oauth2-proxy.github.io/manifests
        targetRevision: "6.2.6"
        chart: oauth2-proxy
        helm:
          values: |-
            fullnameOverride: oauth2-proxy

            config:
              existingSecret: oauth2-proxy-secret

              google:
                existingSecret: oauth2-proxy-secret

              configFile: |-
                # upstreams = [ "file:///dev/null" ]
                upstreams = [ "static://200" ]

                cookie_domains=".{{hostname.public}}"
                email_domains = ["*"]
                whitelist_domains = [".{{hostname.public}}"]

                set_xauthrequest = true
                set_authorization_header = true
                pass_authorization_header = true
                pass_host_header = true
                pass_access_token = true

                reverse_proxy = true
                skip_jwt_bearer_tokens = true
                silence_ping_logging = true

                redirect_url = "https://auth.{{hostname.public}}/oauth2/callback"

                oidc_issuer_url = "https://accounts.google.com"

            extraObjects:
              - apiVersion: external-secrets.io/v1beta1
                kind: ExternalSecret
                metadata:
                  name: oauth2-proxy-secret
                spec:
                  refreshInterval: 1h
                  secretStoreRef:
                    kind: ClusterSecretStore
                    name: parameter-store
                  target:
                    name: oauth2-proxy-secret
                  data:
                    - secretKey: client-id
                      remoteRef:
                        key: /k8s/common/google-id
                    - secretKey: client-secret
                      remoteRef:
                        key: /k8s/common/google-secret
                    - secretKey: cookie-secret
                      remoteRef:
                        key: /k8s/common/cookie-secret

              - apiVersion: networking.istio.io/v1beta1
                kind: Gateway
                metadata:
                  name: oauth2-proxy
                spec:
                  selector:
                    istio: ingressgateway
                  servers:
                    - hosts:
                        - "auth.{{hostname.public}}"
                      port:
                        number: 80
                        name: http
                        protocol: HTTP

              - apiVersion: networking.istio.io/v1beta1
                kind: VirtualService
                metadata:
                  name: oauth2-proxy
                spec:
                  hosts:
                    - "auth.{{hostname.public}}"
                  gateways:
                    - oauth2-proxy
                    - mesh
                  http:
                    - route:
                        - destination:
                            host: oauth2-proxy
                            port:
                              number: 80

              - apiVersion: security.istio.io/v1beta1
                kind: AuthorizationPolicy
                metadata:
                  name: oauth-policy
                  namespace: istio-system
                spec:
                  selector:
                    matchLabels:
                      istio: ingressgateway
                  action: CUSTOM
                  provider:
                    name: oauth2-proxy
                  rules:
                  - to:
                    - operation:
                        hosts:
                        - "rollouts.{{hostname.public}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
