apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: promtail
spec:
  generators:
    - git:
        repoURL: https://github.com/opspresso/argocd-env-addons.git
        revision: HEAD
        files:
          - path: "env/eks-demo.yaml"
          # - path: "env/eks-demo-a.yaml"
          # - path: "env/eks-demo-b.yaml"

  template:
    metadata:
      name: "promtail-{{cluster}}"
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: noti-argocd-{{env}}-addon
      labels:
        app.kubernetes.io/instance: "addons-{{cluster}}"
        krmt.io/cluster: "{{cluster}}"
        krmt.io/group: "addons"
    spec:
      project: addons
      destination:
        name: "{{cluster}}"
        namespace: addon-promtail
      source:
        repoURL: https://grafana.github.io/helm-charts
        targetRevision: "6.2.0"
        chart: promtail
        helm:
          values: |-
            fullnameOverride: promtail

            podLabels:
              owner: "{{cluster}}"
              department: "addons"

            image:
              registry: {{promtail.image.registry}}
              repository: {{promtail.image.repository}}

            extraArgs:
              - -client.external-labels=cluster={{cluster}}

            config:
              lokiAddress: http://{{loki.hostname}}/loki/api/v1/push

            tolerations:
              - operator: Exists

            updateStrategy:
              rollingUpdate:
                maxUnavailable: 25%

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
