apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: addons
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/opspresso/argocd-env-addons
  destinations:
  - name: in-cluster
    namespace: argocd
  - name: in-cluster
    namespace: addon-external-secrets
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/opspresso/argocd-env-demo
  destinations:
  - name: in-cluster
    namespace: argocd
  - name: in-cluster
    namespace: agent-studio
  - name: in-cluster
    namespace: agent-memory
  - name: in-cluster
    namespace: agent-mcps
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
