argo-cd:
  fullnameOverride: argocd


  controller:
    metrics:
      serviceMonitor:
        enabled: False
        selector:
          release: prometheus-eks-demo

  server:
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "argocd.demo.opspresso.com"
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
        service.beta.kubernetes.io/aws-load-balancer-ip-address-type: "dualstack"
        service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:ap-northeast-2:396608815058:certificate/2976f231-8c30-4048-81f0-2e4e2a10fb44"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

    metrics:
      serviceMonitor:
        enabled: False
        selector:
          release: prometheus-eks-demo

  repoServer:
    metrics:
      serviceMonitor:
        enabled: False
        selector:
          release: prometheus-eks-demo

  dex:
    metrics:
      serviceMonitor:
        enabled: False
        selector:
          release: prometheus-eks-demo

  notifications:
    argocdUrl: https://argocd.demo.opspresso.com

  configs:
    rbac:
      policy.default: "role:readonly"
      policy.csv: |
        g, opspresso:sre, role:admin

    cm:
      url: https://argocd.demo.opspresso.com

      help.chatUrl: "https://app.slack.com/client/T03FUG4UB/C035P1YD72A"
      help.chatText: "Chat now!"

      dex.config: |
        connectors:
        - type: github
          id: github
          name: github
          config:
            clientID: $dex.github.clientId
            clientSecret: $dex.github.clientSecret
            teamNameField: slug
            orgs:
              - name: opspresso
        staticClients:
        - id: argo-workflows-sso
          name: Argo Workflow
          redirectURIs:
            - https://workflows.demo.opspresso.com/oauth2/callback
          secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
        - id: oauth2-proxy-sso
          name: OAuth2 Proxy
          redirectURIs:
            - https://auth.demo.opspresso.com/oauth2/callback
          secretEnv: OAUTH2_PROXY_SSO_CLIENT_SECRET

raw:
  resources:
    - apiVersion: networking.istio.io/v1beta1
      kind: Gateway
      metadata:
        name: argocd-server
      spec:
        selector:
          istio: ingressgateway
        servers:
          - hosts:
              - "argocd.demo.opspresso.com"
            port:
              number: 80
              name: http
              protocol: HTTP

    - apiVersion: networking.istio.io/v1beta1
      kind: VirtualService
      metadata:
        name: argocd-server
      spec:
        hosts:
          - "argocd.demo.opspresso.com"
        gateways:
          - argocd-server
          - mesh
        http:
          - route:
              - destination:
                  host: argocd-server
                  port:
                    number: 80

    - apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: argocd-secret
      spec:
        refreshInterval: 1h
        secretStoreRef:
          kind: ClusterSecretStore
          name: parameter-store
        target:
          name: argocd-secret
        data:
          - secretKey: admin.password
            remoteRef:
              key: /k8s/common/argocd-password
          - secretKey: admin.passwordMtime
            remoteRef:
              key: /k8s/common/argocd-mtime
          - secretKey: dex.github.clientId
            remoteRef:
              key: /k8s/opspresso/argocd-github-id
          - secretKey: dex.github.clientSecret
            remoteRef:
              key: /k8s/opspresso/argocd-github-secret
          - secretKey: webhook.github.secret
            remoteRef:
              key: /k8s/common/argocd-webhook
          - secretKey: server.secretkey
            remoteRef:
              key: /k8s/common/argocd-server-secret

          - secretKey: argo-workflows-client-secret
            remoteRef:
              key: /k8s/common/argo-workflows-client-secret
          - secretKey: oauth2-proxy-client-secret
            remoteRef:
              key: /k8s/common/oauth2-proxy-client-secret
