loki-stack:
  loki:
    fullnameOverride: loki

    # podLabels:
    #   owner: "{{cluster}}"
    #   department: "addons"

    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus-{{cluster}}

{% if monitoring is defined %}
{% if monitoring.nodeSelector is defined %}
    tolerations:
      - key: group
        operator: Equal
        value: "{{monitoring.nodeSelector}}"
        effect: NoSchedule
    nodeSelector:
      group: "{{monitoring.nodeSelector}}"
{% endif %}
{% endif %}

raw:
  resources:
    - apiVersion: networking.istio.io/v1beta1
      kind: Gateway
      metadata:
        name: loki
      spec:
        selector:
          istio: ingressgateway
        servers:
          - hosts:
              - "{{loki.hostname}}"
            port:
              number: 80
              name: http
              protocol: HTTP

    - apiVersion: networking.istio.io/v1beta1
      kind: VirtualService
      metadata:
        name: loki
      spec:
        hosts:
          - "{{loki.hostname}}"
        gateways:
          - loki
          - mesh
        http:
          - route:
              - destination:
                  host: loki
                  port:
                    number: 3100
