argo-workflows:
  fullnameOverride: argo-workflows

  controller:
    revisionHistoryLimit: 2

    workflowNamespaces:
      - default



  server:
    revisionHistoryLimit: 2

    # replicas: 1

    extraArgs:
      - --auth-mode=sso



    podAnnotations:
      link.argocd.argoproj.io/external-link: "https://workflows.demo.opspresso.com"

    ingress:
      enabled: false



raw:
  resources:
    - apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: argo-workflows-secret
      spec:
        refreshInterval: 1h
        secretStoreRef:
          kind: ClusterSecretStore
          name: parameter-store
        target:
          name: argo-workflows-secret
        data:
          - secretKey: client-id
            remoteRef:
              key: /k8s/common/argo-workflows-client-id
          - secretKey: client-secret
            remoteRef:
              key: /k8s/common/argo-workflows-client-secret