aws-ebs-csi-driver:
  fullnameOverride: aws-ebs-csi-driver

  storageClasses:
    - name: gp3
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
      volumeBindingMode: WaitForFirstConsumer
      reclaimPolicy: Retain
      parameters:
        type: gp3
        allowAutoIOPSPerGBIncrease: "true" # must quote
      allowVolumeExpansion: true
