atlantis:
  fullnameOverride: atlantis


  atlantisUrl: "https://atlantis.demo.opspresso.com"

  orgAllowlist: "github.com/opspresso/terraform-*"

  podTemplate:
    annotations:
      link.argocd.argoproj.io/external-link: "https://atlantis.demo.opspresso.com"

  ingress:
    enabled: true
    host: "atlantis-public.demo.opspresso.com"
    paths:
      - path: /events
        service: atlantis
        port: 80

  extraManifests:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: atlantis-configmap
      data:
        ATLANTIS_GH_ORG: "opspresso"
        ATLANTIS_GH_USER: "nalbam-bot"
        ATLANTIS_WRITE_GIT_CREDS: "true"
        ATLANTIS_ALLOW_FORK_PRS: "true"


    - apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: atlantis-secret
      spec:
        refreshInterval: 1h
        secretStoreRef:
          kind: ClusterSecretStore
          name: parameter-store
        target:
          name: atlantis-secret
        data:
          - secretKey: ATLANTIS_GH_TOKEN
            remoteRef:
              key: /k8s/common/github/nalbam-bot/token
          - secretKey: ATLANTIS_GH_WEBHOOK_SECRET
            remoteRef:
              key: /k8s/common/github/nalbam-bot/secret


    - apiVersion: networking.istio.io/v1beta1
      kind: Gateway
      metadata:
        name: atlantis
      spec:
        selector:
          istio: ingressgateway
        servers:
          - hosts:
              - "atlantis.demo.opspresso.com"
            port:
              number: 80
              name: http
              protocol: HTTP

    - apiVersion: networking.istio.io/v1beta1
      kind: VirtualService
      metadata:
        name: atlantis
      spec:
        hosts:
          - "atlantis.demo.opspresso.com"
        gateways:
          - atlantis
          - mesh
        http:
          - route:
              - destination:
                  host: atlantis
                  port:
                    number: 80

    - apiVersion: security.istio.io/v1beta1
      kind: AuthorizationPolicy
      metadata:
        name: atlantis
        namespace: istio-system
      spec:
        selector:
          matchLabels:
            istio: ingressgateway
        action: CUSTOM
        provider:
          name: oauth2-proxy
        rules:
        - to:
          - operation:
              hosts:
              - "atlantis.demo.opspresso.com"
