atlantis:
  fullnameOverride: atlantis


  atlantisUrl: "https://atlantis.demo.opspresso.com"

  orgAllowlist: "github.com/opspresso/terraform-*"

  podTemplate:
    annotations:
      link.argocd.argoproj.io/external-link: "https://atlantis.demo.opspresso.com"

  extraManifests:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: atlantis-configmap
      data:
        ATLANTIS_GH_ORG: "opspresso"
        ATLANTIS_GH_USER: "nalbam-bot"
        ATLANTIS_WRITE_GIT_CREDS: "true"
        ATLANTIS_ALLOW_FORK_PRS: "true"


    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      metadata:
        name: atlantis-secret
      spec:
        refreshInterval: 1h
        secretStoreRef:
          kind: ClusterSecretStore
          name: parameter-store
        target:
          name: atlantis-secret
        data:
          - secretKey: ATLANTIS_GH_TOKEN
            remoteRef:
              key: /k8s/common/github/nalbam-bot/token
          - secretKey: ATLANTIS_GH_WEBHOOK_SECRET
            remoteRef:
              key: /k8s/common/github/nalbam-bot/secret


    - apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: atlantis
      spec:
        parentRefs:
          - name: istio-ingressgateway
            namespace: istio-system
        hostnames:
          - "atlantis.demo.opspresso.com"
        rules:
          - backendRefs:
              - name: atlantis
                port: 80

    - apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: atlantis-public
      spec:
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: istio-ingressgateway
            namespace: istio-system
        hostnames:
          - "atlantis-public.demo.opspresso.com"
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /events
            backendRefs:
              - group: ""
                kind: Service
                name: atlantis
                port: 80
                weight: 1

    - apiVersion: security.istio.io/v1beta1
      kind: AuthorizationPolicy
      metadata:
        name: atlantis
        namespace: istio-system
      spec:
        selector:
          matchLabels:
            istio: ingressgateway
        action: CUSTOM
        provider:
          name: oauth2-proxy
        rules:
        - to:
          - operation:
              hosts:
              - "atlantis.demo.opspresso.com"
