apiVersion: v2
description: A Helm chart for Kubernetes
name: grafana
type: application
version: "7.3.0"

dependencies:
- name: grafana
  repository: https://grafana.github.io/helm-charts
  version: "7.3.0"

- name: raw
  repository: https://charts.helm.sh/incubator
  version: "0.2.5"
