grapana:
  fullnameOverride: grafana

{% if grafana is defined %}
  podLabels:
    owner: "{{cluster}}"
    department: "addons"

  podAnnotations:
    link.argocd.argoproj.io/external-link: "https://{{grafana.hostname}}"

  grafana.ini:
    server:
      root_url: "https://{{grafana.hostname}}/"

    # https://grafana.com/docs/grafana/latest/auth/github/
    auth.github:
      enabled: {{grafana.auth.github.enabled}}
      allow_sign_up: false
      client_id: $__file{/etc/secrets/grafana-secret/github-id}
      client_secret: $__file{/etc/secrets/grafana-secret/github-secret}
      scopes: user:email,read:org
      auth_url: https://github.com/login/oauth/authorize
      token_url: https://github.com/login/oauth/access_token
      api_url: https://api.github.com/user
      allowed_organizations: {{grafana.auth.github.org}}
      # team_ids: {{grafana.auth.github.team_ids}}

    # https://grafana.com/docs/grafana/latest/auth/google/
    auth.google:
      enabled: {{grafana.auth.google.enabled}}
      allow_sign_up: false
      client_id: $__file{/etc/secrets/grafana-secret/google-id}
      client_secret: $__file{/etc/secrets/grafana-secret/google-secret}
      scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
      auth_url: https://accounts.google.com/o/oauth2/auth
      token_url: https://accounts.google.com/o/oauth2/token
      allowed_domains: {{grafana.auth.google.allowed_domains}}

  ingress:
    enabled: false

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-prometheus.addon-prometheus.svc.cluster.local:9090
        access: proxy
        isDefault: true
      - name: demo
        type: prometheus
        url: {{grafana.datasource.demo}}
        access: proxy
      - name: demo-a
        type: prometheus
        url: {{grafana.datasource.demo_a}}
        access: proxy
      - name: demo-b
        type: prometheus
        url: {{grafana.datasource.demo_b}}
        access: proxy
      - name: Loki
        type: loki
        url: {{grafana.datasource.loki}}
        access: proxy

  serviceMonitor:
    enabled: true
    labels:
      release: prometheus-{{cluster}}

raw:
  resources:
    - apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: grafana-secret
      spec:
        refreshInterval: 1h
        secretStoreRef:
          kind: ClusterSecretStore
          name: parameter-store
        target:
          name: grafana-secret
        data:
          - secretKey: admin-user
            remoteRef:
              key: /k8s/common/admin-user
          - secretKey: admin-password
            remoteRef:
              key: /k8s/common/admin-password
          - secretKey: github-id
            remoteRef:
              key: /k8s/{{grafana.auth.github.org}}/grafana-github-id
          - secretKey: github-secret
            remoteRef:
              key: /k8s/{{grafana.auth.github.org}}/grafana-github-secret
          - secretKey: google-id
            remoteRef:
              key: /k8s/common/google-id
          - secretKey: google-secret
            remoteRef:
              key: /k8s/common/google-secret

    - apiVersion: networking.istio.io/v1beta1
      kind: Gateway
      metadata:
        name: grafana
        annotations:
          link.argocd.argoproj.io/external-link: "https://{{grafana.hostname}}"
      spec:
        selector:
          istio: ingressgateway
        servers:
          - hosts:
              - "{{grafana.hostname}}"
            port:
              number: 80
              name: http
              protocol: HTTP

    - apiVersion: networking.istio.io/v1beta1
      kind: VirtualService
      metadata:
        name: grafana
      spec:
        hosts:
          - "{{grafana.hostname}}"
        gateways:
          - grafana
          - mesh
        http:
          - route:
              - destination:
                  host: grafana
                  port:
                    number: 80
{% endif %}
