fullnameOverride: argocd

## Globally shared configuration
global:
  # -- Default domain used by all components
  ## Used for ingresses, certificates, SSO, notifications, etc.
  domain: ARGOCD_HOSTNAME

server:
  replicas: 2

  service:
    type: LoadBalancer
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "ARGOCD_HOSTNAME"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
      service.beta.kubernetes.io/aws-load-balancer-ip-address-type: "dualstack"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "AWS_ACM_CERT"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

repoServer:
  replicas: 2

configs:
  rbac:
    policy.default: "role:readonly"
    policy.csv: |
      g, GITHUB_ORG:GITHUB_TEAM, role:admin

  params:
    server.insecure: true

  cm:
    url: https://ARGOCD_HOSTNAME

    dex.config: |
      connectors:
      - type: github
        id: github
        name: github
        config:
          clientID: $dex.github.clientId
          clientSecret: $dex.github.clientSecret
          teamNameField: slug
          orgs:
            - name: GITHUB_ORG

  secret:
    createSecret: true

    githubSecret: "ARGOCD_WEBHOOK"

    extra:
      server.secretkey: "ARGOCD_SERVER_SECRET"

      dex.github.clientId: "ARGOCD_GITHUB_ID"
      dex.github.clientSecret: "ARGOCD_GITHUB_SECRET"

    # Argo expects the password in the secret to be bcrypt hashed. You can create this hash with
    # `htpasswd -nbBC 10 "" $PASSWORD | tr -d ':\n' | sed 's/$2y/$2a/'`
    argocdServerAdminPassword: "ARGOCD_PASSWORD"
    # Password modification time defaults to current time if not set
    argocdServerAdminPasswordMtime: "ARGOCD_MTIME"

  repositories:
    env-addons-repo:
      name: env-addons
      type: git
      url: https://github.com/opspresso/argocd-env-addons
    env-demo-repo:
      name: env-demo
      type: git
      url: https://github.com/opspresso/argocd-env-demo
    opspresso-repo:
      name: opspresso
      type: helm
      url: https://opspresso.github.io/helm-charts

extraObjects:
  - apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      name: addons
    spec:
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      destinations:
        - name: '*'
          namespace: '*'
          server: '*'
      sourceRepos:
        - '*'

  - apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      name: apps
    spec:
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      destinations:
        - name: '*'
          namespace: '*'
          server: '*'
      sourceRepos:
        - '*'
