ingress-nginx:
  fullnameOverride: ingress-nginx

  controller:
    replicaCount: "3"

    stats:
      enabled: False

    metrics:
      enabled: False
      serviceMonitor:
        enabled: False

tgb:
  resources:
    - apiVersion: elbv2.k8s.aws/v1beta1
      kind: TargetGroupBinding
      metadata:
        name: ingress-nginx-public
      spec:
        serviceRef:
          name: ingress-nginx-controller
          port: http
        targetGroupARN: "arn:aws:elasticloadbalancing:ap-northeast-2:396608815058:targetgroup/demo-http-b/eee2c9eeccac5e8b"
        targetType: ip

    - apiVersion: elbv2.k8s.aws/v1beta1
      kind: TargetGroupBinding
      metadata:
        name: ingress-nginx-internal
      spec:
        serviceRef:
          name: ingress-nginx-controller
          port: http
        targetGroupARN: "arn:aws:elasticloadbalancing:ap-northeast-2:396608815058:targetgroup/demo-in-http-b/c58aa00f37da3d17"
        targetType: ip