grafana:
  fullnameOverride: grafana


  podLabels:
    owner: "eks-demo"
    department: "addons"

  podAnnotations:
    link.argocd.argoproj.io/external-link: "https://grafana.demo.opspresso.com"

  grafana.ini:
    server:
      root_url: "https://grafana.demo.opspresso.com/"

    # https://grafana.com/docs/grafana/latest/auth/github/
    auth.github:
      enabled: True
      allow_sign_up: false
      client_id: $__file{/etc/secrets/grafana-secret/github-id}
      client_secret: $__file{/etc/secrets/grafana-secret/github-secret}
      scopes: user:email,read:org
      auth_url: https://github.com/login/oauth/authorize
      token_url: https://github.com/login/oauth/access_token
      api_url: https://api.github.com/user
      allowed_organizations: opspresso
      # team_ids: sre

    # https://grafana.com/docs/grafana/latest/auth/google/
    auth.google:
      enabled: False
      allow_sign_up: false
      client_id: $__file{/etc/secrets/grafana-secret/google-id}
      client_secret: $__file{/etc/secrets/grafana-secret/google-secret}
      scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
      auth_url: https://accounts.google.com/o/oauth2/auth
      token_url: https://accounts.google.com/o/oauth2/token
      allowed_domains: nalbam.com daangn.com

  ingress:
    enabled: false

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-prometheus.addon-prometheus.svc.cluster.local:9090
        access: proxy
        isDefault: true
      - name: demo
        type: prometheus
        url: http://prom.in.demo.opspresso.com
        access: proxy
      - name: demo-a
        type: prometheus
        url: http://prom.in.demo-a.opspresso.com
        access: proxy
      - name: demo-b
        type: prometheus
        url: http://prom.in.demo-b.opspresso.com
        access: proxy
      - name: Loki
        type: loki
        url: http://loki.in.demo.opspresso.com
        access: proxy

  serviceMonitor:
    enabled: true
    labels:
      release: prometheus-eks-demo

raw:
  resources:
    - apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: grafana-secret
      spec:
        refreshInterval: 1h
        secretStoreRef:
          kind: ClusterSecretStore
          name: parameter-store
        target:
          name: grafana-secret
        data:
          - secretKey: admin-user
            remoteRef:
              key: /k8s/common/admin-user
          - secretKey: admin-password
            remoteRef:
              key: /k8s/common/admin-password
          - secretKey: github-id
            remoteRef:
              key: /k8s/opspresso/grafana-github-id
          - secretKey: github-secret
            remoteRef:
              key: /k8s/opspresso/grafana-github-secret
          - secretKey: google-id
            remoteRef:
              key: /k8s/common/google-id
          - secretKey: google-secret
            remoteRef:
              key: /k8s/common/google-secret

    - apiVersion: networking.istio.io/v1beta1
      kind: Gateway
      metadata:
        name: grafana
        annotations:
          link.argocd.argoproj.io/external-link: "https://grafana.demo.opspresso.com"
      spec:
        selector:
          istio: ingressgateway
        servers:
          - hosts:
              - "grafana.demo.opspresso.com"
            port:
              number: 80
              name: http
              protocol: HTTP

    - apiVersion: networking.istio.io/v1beta1
      kind: VirtualService
      metadata:
        name: grafana
      spec:
        hosts:
          - "grafana.demo.opspresso.com"
        gateways:
          - grafana
          - mesh
        http:
          - route:
              - destination:
                  host: grafana
                  port:
                    number: 80
