cert-manager:
  fullnameOverride: cert-manager

  ingressShim:
    defaultIssuerKind: ClusterIssuer
    defaultIssuerName: letsencrypt-issuer

  installCRDs: true

cert-manager-extra:
  fullnameOverride: cert-manager-extra

  resources:
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: cluster-issuer-selfsigned
      spec:
        selfSigned: {}
