aws-ebs-csi-driver:
  image:
    repository: "public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver"

  sidecars:
    nodeDriverRegistrar:
      image:
        repository: "k8s.gcr.io/sig-storage/csi-node-driver-registrar"
    livenessProbe:
      image:
        repository: "k8s.gcr.io/sig-storage/livenessprobe"

  controller:
    podLabels:
      department: "addons"
      owner: "eks-demo-a"

    k8sTagClusterId: "eks-demo-a"

    extraVolumeTags:
      KubernetesCluster: "eks-demo-a"
      Environment: "demo"

    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::082867736673:role/irsa--eks-demo-a--aws-ebs-csi-driver"

  node:
    podLabels:
      department: "addons"
      owner: "eks-demo-a"

    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::082867736673:role/irsa--eks-demo-a--aws-ebs-csi-driver"

  useOldCSIDriver: False