argo-workflows:
  controller:
    podLabels:
      department: addons
      owner: '{{cluster}}'
    workflowNamespaces:
    - default
  fullnameOverride: argo-workflows
  server:
    extraArgs:
    - --auth-mode=sso
    podLabels:
      department: addons
      owner: '{{cluster}}'
    replicas: 1
    sso:
      clientId:
        key: client-id
        name: argo-workflows-secret
      clientSecret:
        key: client-secret
        name: argo-workflows-secret
      issuer: https://{{argocd.hostname}}/api/dex
      rbac:
        enabled: true
      redirectUrl: https://workflows.{{hostname.public}}/oauth2/callback
      scopes:
      - groups
  workflow:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::{{aws_account_id}}:role/irsa--{{cluster}}--argo-workflows
      create: true
