apiVersion: v2
description: A Helm chart for Kubernetes
name: argocd
type: application
version: "6.7.2" # helm chart argocd version

dependencies:
- name: argo-cd
  alias: argocd
  repository: https://argoproj.github.io/argo-helm
  version: "6.7.2" # helm chart argocd version

- name: raw
  repository: https://charts.helm.sh/incubator
  version: "0.2.5" # helm chart raw version
