kite:
  fullnameOverride: kite
  resources:
    requests: {cpu: 100m, memory: 128Mi}
    limits: {memory: 512Mi}

  # sqlite on a ReadWriteOnce PVC cannot RollingUpdate
  deploymentStrategy:
    type: Recreate

  db:
    type: sqlite
    sqlite:
      persistence:
        pvc:
          enabled: true
          storageClass: gp3 # aws-ebs-sc
          size: 1Gi
