apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-k3s
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: addons
  destination:
    name: in-cluster
    namespace: cert-manager
  source:
    repoURL: https://github.com/opspresso/argocd-env-addons.git
    targetRevision: HEAD
    path: charts/cert-manager
    helm:
      releaseName: cert-manager
      valueFiles:
        - values.yaml
        - k3s/values-k3s-demo.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
