apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-crds-k3s
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: addons
  destination:
    name: in-cluster
    namespace: addon-gateway-api-crds
  source:
    repoURL: https://github.com/opspresso/argocd-env-addons.git
    targetRevision: HEAD
    path: charts/gateway-api-crds
    helm:
      valueFiles:
        - values.yaml
        - k3s/values-k3s-demo.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
