apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-k3s
  namespace: argocd
spec:
  project: addons
  destination:
    name: in-cluster
    namespace: addon-grafana
  source:
    repoURL: https://github.com/opspresso/argocd-env-addons.git
    targetRevision: HEAD
    path: charts/grafana
    helm:
      valueFiles:
        - values.yaml
        - k3s/values-k3s-demo.yaml
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
