apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-k3s
  namespace: argocd
spec:
  project: addons
  destination:
    name: in-cluster
    namespace: addon-victoria-metrics
  source:
    repoURL: https://github.com/opspresso/argocd-env-addons.git
    targetRevision: HEAD
    path: charts/victoria-metrics
    helm:
      valueFiles:
        - values.yaml
        - k3s/values-k3s-demo.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
