{{- $argocd := index .Values "argo-cd" }}
{{- if $argocd.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: argocd-gateway
  namespace: argocd
spec:
  gatewayClassName: traefik
  listeners:
    - name: https
      hostname: {{ $argocd.gateway.hostname | quote }}
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: argocd-server-tls
      allowedRoutes:
        namespaces:
          from: Same
{{- end }}
